services:
  db:
    image: pgvector/pgvector:pg16
    container_name: traffic-chatbot
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc12345
      POSTGRES_DB: traffic_chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:docker rm -f traffic-chatbot