# Generated by Django 5.2.12 on 2026-04-07 08:45

from django.db import migrations, models
from pgvector.django import VectorField, VectorExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='TrafficLawChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', VectorField(dimensions=384)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
