# Generated by Django 5.2.12 on 2026-04-07 08:48

from django.db import migrations
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlawchunk',
            name='embedding',
            field=VectorField(dimensions=768),
        ),
    ]
