# Generated by Django 5.2.12 on 2026-04-09 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_update_embedding_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlawchunk',
            name='metadata',
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='chunk_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='dieu_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='dieu_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='has_revocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='khoan_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='penalty_max',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='penalty_min',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='vehicle_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='violation_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trafficlawchunk',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='trafficlawchunk',
            index=models.Index(fields=['source'], name='rag_app_tra_source_8ee628_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlawchunk',
            index=models.Index(fields=['dieu_num'], name='rag_app_tra_dieu_nu_4c99c2_idx'),
        ),
    ]
