# Generated by Django 5.2.12 on 2026-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_remove_trafficlawchunk_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trafficlawchunk',
            name='rag_app_tra_source_8ee628_idx',
        ),
        migrations.RemoveIndex(
            model_name='trafficlawchunk',
            name='rag_app_tra_dieu_nu_4c99c2_idx',
        ),
        migrations.RemoveField(
            model_name='trafficlawchunk',
            name='chunk_type',
        ),
        migrations.RemoveField(
            model_name='trafficlawchunk',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trafficlawchunk',
            name='has_revocation',
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='authorities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='diem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trafficlawchunk',
            name='point_deduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trafficlawchunk',
            name='dieu_title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trafficlawchunk',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='trafficlawchunk',
            table='traffic_law_chunks',
        ),
    ]
